# Generated by Django 3.0.5 on 2020-04-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_medicalprofile_patientprofile_physiotherapistprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='physiotherapistprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='MedicalProfile',
        ),
        migrations.DeleteModel(
            name='PatientProfile',
        ),
        migrations.DeleteModel(
            name='PhysiotherapistProfile',
        ),
    ]
