# Generated by Django 3.0.5 on 2020-04-25 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_categoriaproducto_cliente_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='categoriaProducto',
        ),
        migrations.DeleteModel(
            name='producto',
        ),
    ]
