# Generated by Django 3.0.5 on 2020-05-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20200504_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'ordering': ['id'], 'verbose_name': 'categoriaProducto', 'verbose_name_plural': 'categoriaProducto'},
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
